package raBi;

public class cntrol_flow_try_catch
{

	public static void main(String[] args)
	{
		/*try
		{
			System.out.println("Hello world");  //CASE 1
			System.out.println(10/5);
			System.out.println("hello India");
		}
		catch (ArithmeticException e)
		{
			System.out.println(10/5);  //when there is no any exceptions in try then CATCH will not execute
			System.out.println("hello Banglore");
		}
		System.out.println("hello Dhanbad");*/
		
		
		
		/*try
		{
			System.out.println("Hello world");   //CASE 2
			System.out.println(10/0);  //here an arithmetic exceptions , so from here it will go to CATCH 
			System.out.println("hello India"); //block and leave it
		}
		catch (ArithmeticException e)
		{
			System.out.println(10/5);
			System.out.println("hello banglore");
		}
		System.out.println("hello dhanbad");*/
		
		
		/*try
		{
			System.out.println("Hello world");  //CASE 3
			System.out.println(10/0);   // if Exception raised but no any CATCH BLOCK, then it is an 
			System.out.println("hello india");   //abnormal termination
		}
		finally
		{
		System.out.println("hello dhanbad");
		}*/
		
		
		
		
		/*try
		{
			System.out.println("Hello world");  //CASE 4
			System.out.println(10/5);
			System.out.println("hello india");
		}
		catch (ArithmeticException e)
		{
			System.out.println(10/0);  //if exception is in CATCH BLOCK, then
			System.out.println("hello banglore");
		}
		System.out.println("hello dhanbad");*/
		
		
		
		

	}

}
